POST http://localhost:5000/creategame HTTP/1.1
Content-Type: application/json

{
    "names":{
        "game":"asdf",
        "blue":"BLUETEAM",
        "red":"REDTEAM"
    },
    "time":{
        "pick": 1,
        "swap": 1000,
        "ban": 1
    }
}
